//
//  AddServerPresenter.swift
//  MeReachApp
//
//  Created by Marina Miranda Aranha on 17/09/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddServerPresentationLogic
{
    func presentAddedServer(response: AddServer.AddServer.Response)

}

class AddServerPresenter: AddServerPresentationLogic
{
  weak var viewController: AddServerDisplayLogic?
  
    func presentAddedServer(response: AddServer.AddServer.Response)
    {
      let viewModel = AddServer.AddServer.ViewModel(server: response.server)
      viewController?.displayAddedServer(viewModel: viewModel)
    }
}
