//
//  AddServerModels.swift
//  MeReachApp
//
//  Created by Marina Miranda Aranha on 17/09/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AddServer
{
    struct ServerFormFields
    {
      var name: String
      var url: String
      var status: String
    }
    
    enum AddServer
    {
      struct Request
      {
        var serverFormFields: ServerFormFields
      }
      struct Response
      {
        var server: Server?
      }
      struct ViewModel
      {
        var server: Server?
      }
    }
}
