//
//  AddServerRouter.swift
//  MeReachApp
//
//  Created by Marina Miranda Aranha on 17/09/20.
//  Copyright (c) 2020. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddServerRoutingLogic {
    func routeToListServers(segue: UIStoryboardSegue?)
}

protocol AddServerDataPassing {
    var dataStore: AddServerDataStore? { get }
}

class AddServerRouter: NSObject, AddServerRoutingLogic, AddServerDataPassing {
    weak var viewController: AddServerViewController?
    var dataStore: AddServerDataStore?
  
    // MARK: Routing
  
    func routeToListServers(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ListServersViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToListServers(source: dataStore!, destination: &destinationDS)
        } else {
            let index = viewController!.navigationController!.viewControllers.count - 2
            let destinationVC = viewController?.navigationController?.viewControllers[index] as! ListServersViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToListServers(source: dataStore!, destination: &destinationDS)
            navigateToListServers(source: viewController!, destination: destinationVC)
        }
    }

    // MARK: Navigation
  
    func navigateToListServers(source: AddServerViewController, destination: ListServersViewController) {
        source.navigationController?.popViewController(animated: true)
    }
  
    // MARK: Passing data
    
    func passDataToListServers(source: AddServerDataStore, destination: inout ListServersDataStore){
    }
}
