//
//  ListServersPresenter.swift
//  MeReachApp
//
//  Created by Marina Miranda Aranha on 15/09/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListServersPresentationLogic
{
    func presentFetchedServers(response: ListServers.FetchServers.Response)
}

class ListServersPresenter: ListServersPresentationLogic
{
  weak var viewController: ListServersDisplayLogic?
  
  
// MARK: - Fetch orders
    
  func presentFetchedServers(response: ListServers.FetchServers.Response)
  {
      var displayedServers: [ListServers.FetchServers.ViewModel.DisplayedServer] = []
      for server in response.servers {
        let name = server.name
        let status = server.status
        let url = server.url
        let displayedServer = ListServers.FetchServers.ViewModel.DisplayedServer(name: name, status: status, url: url)
        displayedServers.append(displayedServer)
      }
      let viewModel = ListServers.FetchServers.ViewModel(displayedServers: displayedServers)
      
        DispatchQueue.main.async {
            self.viewController?.displayFetchedServers(viewModel: viewModel)
        }
  }
    
}
