//
//  ListServersRouter.swift
//  MeReachApp
//
//  Created by Marina Miranda Aranha on 15/09/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListServersRoutingLogic {
    func routeToAddServer(segue: UIStoryboardSegue?)
}

protocol ListServersDataPassing {
   var dataStore: ListServersDataStore? { get }
}

class ListServersRouter: NSObject, ListServersRoutingLogic, ListServersDataPassing {
   weak var viewController: ListServersViewController?
   var dataStore: ListServersDataStore?
  
    // MARK: Routing
    
    func routeToAddServer(segue: UIStoryboardSegue?)
    {
      if let segue = segue {
        let destinationVC = segue.destination as! AddServerViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToAddServer(source: dataStore!, destination: &destinationDS)
      } else {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "AddServerViewController") as! AddServerViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToAddServer(source: dataStore!, destination: &destinationDS)
        navigateToAddServer(source: viewController!, destination: destinationVC)
      }
    }
    
    // MARK: Navigation
    
    func navigateToAddServer(source: ListServersViewController, destination: AddServerViewController) {
       source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToAddServer(source: ListServersDataStore, destination: inout AddServerDataStore){
        
    }
    
}
