//
//  ListServersModels.swift
//  MeReachApp
//
//  Created by Marina Miranda Aranha on 15/09/20.
//  Copyright (c) 2020. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListServers {
    
    struct ServerFormFields {
        var name: String
        var status: String
        var url: String
    }
      
   enum FetchServers {
        struct Request{
        }
        struct Response{
            var servers: [Server]
        }
        struct ViewModel{
            struct DisplayedServer{
                var name: String
                var status: String
                var url: String
            }
            var displayedServers: [DisplayedServer]
        }
   }
    
    enum DeleteServer {
          struct Request {
            var serverFormFields: ServerFormFields
          }
          struct Response {
            var server: Server?
          }
          struct ViewModel {
            var server: Server?
      }
    }
    
}
